# TCL File Generated by Component Editor 18.1
# Wed Sep 02 19:07:44 CST 2020
# DO NOT MODIFY


# 
# Kirby_Game_Core "Kirby_Game_Core" v1.0
#  2020.09.02.19:07:44
# This module is used for passing game information
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Kirby_Game_Core
# 
set_module_property DESCRIPTION "This module is used for passing game information"
set_module_property NAME Kirby_Game_Core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "ECE 385 Kirby Game"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Kirby_Game_Core
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_kirby_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_kirby_interface.sv SYSTEM_VERILOG PATH avalon_kirby_interface.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_kirby_interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_kirby_interface.sv SYSTEM_VERILOG PATH avalon_kirby_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CLK
# 
add_interface CLK clock end
set_interface_property CLK clockRate 50000000
set_interface_property CLK ENABLED true
set_interface_property CLK EXPORT_OF ""
set_interface_property CLK PORT_NAME_MAP ""
set_interface_property CLK CMSIS_SVD_VARIABLES ""
set_interface_property CLK SVD_ADDRESS_GROUP ""

add_interface_port CLK CLK clk Input 1


# 
# connection point RESET
# 
add_interface RESET reset end
set_interface_property RESET associatedClock CLK
set_interface_property RESET synchronousEdges DEASSERT
set_interface_property RESET ENABLED true
set_interface_property RESET EXPORT_OF ""
set_interface_property RESET PORT_NAME_MAP ""
set_interface_property RESET CMSIS_SVD_VARIABLES ""
set_interface_property RESET SVD_ADDRESS_GROUP ""

add_interface_port RESET RESET reset Input 1


# 
# connection point Kirby_Slave
# 
add_interface Kirby_Slave avalon end
set_interface_property Kirby_Slave addressUnits WORDS
set_interface_property Kirby_Slave associatedClock CLK
set_interface_property Kirby_Slave associatedReset RESET
set_interface_property Kirby_Slave bitsPerSymbol 8
set_interface_property Kirby_Slave burstOnBurstBoundariesOnly false
set_interface_property Kirby_Slave burstcountUnits WORDS
set_interface_property Kirby_Slave explicitAddressSpan 0
set_interface_property Kirby_Slave holdTime 0
set_interface_property Kirby_Slave linewrapBursts false
set_interface_property Kirby_Slave maximumPendingReadTransactions 0
set_interface_property Kirby_Slave maximumPendingWriteTransactions 0
set_interface_property Kirby_Slave readLatency 0
set_interface_property Kirby_Slave readWaitStates 0
set_interface_property Kirby_Slave readWaitTime 0
set_interface_property Kirby_Slave setupTime 0
set_interface_property Kirby_Slave timingUnits Cycles
set_interface_property Kirby_Slave writeWaitTime 0
set_interface_property Kirby_Slave ENABLED true
set_interface_property Kirby_Slave EXPORT_OF ""
set_interface_property Kirby_Slave PORT_NAME_MAP ""
set_interface_property Kirby_Slave CMSIS_SVD_VARIABLES ""
set_interface_property Kirby_Slave SVD_ADDRESS_GROUP ""

add_interface_port Kirby_Slave AVL_ADDR address Input 4
add_interface_port Kirby_Slave AVL_CS chipselect Input 1
add_interface_port Kirby_Slave AVL_READ read Input 1
add_interface_port Kirby_Slave AVL_WRITE write Input 1
add_interface_port Kirby_Slave AVL_WRITEDATA writedata Input 32
add_interface_port Kirby_Slave AVL_READDATA readdata Output 32
set_interface_assignment Kirby_Slave embeddedsw.configuration.isFlash 0
set_interface_assignment Kirby_Slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment Kirby_Slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment Kirby_Slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Exported_Data
# 
add_interface Exported_Data conduit end
set_interface_property Exported_Data associatedClock CLK
set_interface_property Exported_Data associatedReset RESET
set_interface_property Exported_Data ENABLED true
set_interface_property Exported_Data EXPORT_OF ""
set_interface_property Exported_Data PORT_NAME_MAP ""
set_interface_property Exported_Data CMSIS_SVD_VARIABLES ""
set_interface_property Exported_Data SVD_ADDRESS_GROUP ""

add_interface_port Exported_Data Register_Files export_data Output 512

